### ISSUE TITLE
bootstrapping

### ISSUE THREAD

**Issue by yupinglin0301** [Huang-lab/dementia-survival-prediction#1]
Hi, May I know the bootstrapping is conducted on origin dataset right? Would it cause data leakage? As I saw, you conducted feature selection and hyperparameter work before doing bootstrapping. Thanks.

**Comment by jimmyzhang2003** [comment]
We did, in fact, perform bootstrapping after conducting feature selection and hyperparameter work. In our case, our goal was to just get a general sense of the variability introduced by the data splitting (i.e., by generating 95% CIs), but the main performance metrics we reported were the ones from the original train-test split.

The alternative would have been to just perform k-fold cross validation or bootstrapping before feature selection and hyperparameter optimization, but the performance difference would have been minimal (as you could see, the performance of our original train-test split, which was not affected at all by data leakage, was right in the middle of the 95% CI interval anyways), not to mention the enormous amount of additional time and resources required for training.

In the end, we made a compromise, but it didn't have too meaningful of an impact on our results anyways.
